services:
    spring-boot-service:
        build:
            context: .
        ports:
            - "8080:8080"
        environment:
            "app.logging.enabled": "false"
            "app.thread-executor": "virtual"
        deploy:
            resources:
                limits:
                    cpus: '1.00'
                    memory: 600M